Dev
Profsain/city-weather pull request #2
Opened 2022-08-04 16:14 UTC by Profsain

In this project, I built a weather app using openweathermap API.
- Added app project setup file
- Added UI component
- Fetched weather data from API
- Display weather data in the UI
- Implemented search weather by city name functionality
- Update the Readme file
-
![screencapture-localhost-3000-2022-08-04-12_11_29](https://user-images.githubusercontent.com/32632836/182896732-7abda024-b07d-4cd0-a65e-be9ece7ea0e7.png)

2022-08-04 17:38 UTC, Whoistolu requested changes
Hi @Profsain 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ]  _Check the inline comments under the review for sections to improve._

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-04 17:38 UTC, Whoistolu commented on README.md
> +### Live Demo
- [ ] [REQUIRED] Kindly ensure that this project is been deployed using Heroku, Netlify, or GitHub Pages as stated in the project requirement.

2022-08-04 17:38 UTC, Whoistolu commented on README.md
> +# City-Weather App
- [ ] [REQUIRED] Kindly ensure you make a video presentation of this project with a 5-minute maximum length. Also, ensure the video has a clear presentation of the project with a highlight of a piece of code you are most proud of. This is a core requirement.

2022-08-04 17:38 UTC, Whoistolu commented on README.md
> +Microverse Community
- [ ] [REQUIRED] In the Acknowledgment section, kindly ensure that you give appropriate credit to [Nelson Sakwa](https://www.behance.net/sakwadesignstudio) the [author of the original design](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), as required by the [Creative Commons License](https://creativecommons.org/licenses/) as stated in the project requirement.

2022-08-04 17:38 UTC, Whoistolu commented on README.md
> +### Live Demo
- [ ] [REQUIRED] Kindly ensure that you deploy this application using Heroku, Netlify, or GitHub Pages as stated in the project requirement.

2022-08-04 17:38 UTC, Whoistolu commented on src/components/SingleCard.js
> +);
- [ ] [REQUIRED] You have put a great effort into this project. I can see that whenever search for a state of the country Nigeria, it updates the state and also fetches my current location which is very good. I also discovered that your details are been displayed on that same page. However, note that this project requires that you put the state of the country on the homepage and display its details on the details page. See again the image of the template provided for this project and as I have explained to you on our last call.
### Template Provided
![Screenshot from 2022-08-04 18-36-31](https://user-images.githubusercontent.com/58692590/182915134-1b210885-f95a-42a2-ad11-ff0aaefde314.png)

2022-08-05 23:59 UTC, AmaduKamara requested changes
# Status: Required Changes ♻️♻️♻️ 

Hi @Profsain,

Good job so far on working on the details page and a few other changes asked by the previous reviewer.
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
You did well on the following: 
✅ Used Gitflow correctly
✅ All linter checks passed
✅ Good Descriptive PR
✅ Good commit messages
✅ App is hosted on Netlify 👍 

## Required Changes ♻️
_Check the comments under the review._

The Previous reviewer did not mention this one and it's required for this project 

- [ ] Kindly write tests for this project as it's required you write unit tests for most of your components.
- 
![image](https://user-images.githubusercontent.com/50941074/183224940-c91e0465-34af-4bc0-866c-4bf186d7730a.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-08-05 23:59 UTC, AmaduKamara commented on README.md
> +[Video Demo:](https://www.loom.com/share/0046e2bc7a3b4553b649f7dcd167f784)
Good job on making a video presentation for your project as required by the project and the previous reviewer, but you still have a few more areas to mention in the video that you left out and it is required you mention them in the video.

- [ ] Kindly mention a code section that you are proud of implementing. The idea here is for you to show a basic code section in the project that you feel really proud working on. Please redo the video, and mention that part 👍

2022-08-05 23:59 UTC, AmaduKamara commented on README.md
> +[www.devchallenge.io](https://devchallenges.io/) for the design inspiration
Just as the previous reviewer asked, please give credit to [Nelson Sakwa](https://www.behance.net/sakwadesignstudio) the [author of the original design](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), as required in the project description. Microverse used that design to give you the inspiration to build something similar to it and it is required that you give credit to them.

2022-08-06 09:27 UTC, julie-ify approved these changes
Hi @Profsain,

## Highlights!
- Good feature branch name ✔️ 
- No linter errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-06 09:59 UTC, merged